### ISSUE TITLE
Messages in wrong format

### ISSUE THREAD

**Issue by EstebanMonge** [sebthebert/Octopussy#614]
Hello I have Debian GNU/Linux 7.7 with Octopussy 1.0.14.

I used the
When I check Message I get all messages with wrong format for example:
<@DATE_TIME_ISO:datetime@> <@WORD:device@> <@REGEXP("acpid"):daemon@>: <@REGEXP("client connected.+"):msg@>

What can be wrong?

**Comment by sebthebert** [comment]
No news, good news... I close this ticket.
