### ISSUE TITLE
Logviewer is not working properly

### ISSUE THREAD

**Issue by mdmansoor26** [sebthebert/Octopussy#617]
Hi,

Octopussy version: 1.0.14
OS : CentOS 6.5 Final

Issue: Logviewer is not working properly for All servers

When we select the "Current Date" in Logviewer, the octopussy shows the "Yesterdays or Day before Yesterday's" logs. Attached "Loviewer.png" for your reference please look into "Current Date" and Logs date in attached printshot.

FYI. When i check the log's directly in server under below path, the log path is belongs to 2015-03-11, but  inside the file date shows as "2015-03-08T21:50:01+05:30". Kindly help.

```
[root@octopussy 11]# zcat /var/lib/octopussy/logs/ns6/Unknown/2015/03/11/msg_01h48.log.gz
2015-03-08T21:50:01+05:30 ns6 crond[23513]: (root) CMD (python /public/gdp/OPSScript/zabbix/sem_service_status.py |/usr/local/bin/zabbix_sender -z 172.17.30.1 -c /usr/local/etc/zabbix_agentd.conf -i - 2>>/tmp/ga_zabbix_bm.log > /dev/null)
[root@octopussy 11]# 
```

![logviewer](https://cloud.githubusercontent.com/assets/8190731/6609149/2b4f3b72-c874-11e4-88c4-ce89a4020ab8.png)

Best regards,
Md. Mansoor

**Comment by sebthebert** [comment]
Wow...

I don't really know how it can be possible...

I'll be away from my computer this week-end, I will take a look at the code next week, 
but I'm not sure to figure out what's the problem...

Have you done anything special with these logs ? 
The problem is only for this device ? 
The problem is for all logs of this device or only a timeperiod ?
Is this device in the same timezone as Octopussy server ?


Regards,

**Comment by mdmansoor26** [comment]
Thanks for the quick reply! Kindly find my response below.

Have you done anything special with these logs ? No
The problem is only for this device ? No for all devices
The problem is for all logs of this device or only a timeperiod ? For All Logs
Is this device in the same timezone as Octopussy server ? No. Device in GMT Octopussy running in IST

Note: I have installed octpussy with IST timezone, please guide me to change the octopussy from IST to GMT. We can identify were timezone is the issue or not.

Best regards,
Md. Mansoor

**Comment by mdmansoor26** [comment]
To make it clear, I have checked some interesting things on this issue.

1. The log file store's with different timing is due to TimeZone difference between octopussy server and Devices. After we restart the octopussy service now we are getting yesterday's log in today's .gz file

Example:  The file is belongs to 2015-03-13 but inside the file date shows as 2015-03-12. So it's confirmed that due to TimeZone difference logs are creating like below. We can ignore this issue as we will update this at our end.

[root@octopussy 03]# zcat /var/lib/octopussy/logs/ns6/Unknown/2015/03/13/msg_14h54.log.gz 
2015-03-12T03:22:01+05:30 ns6 crond[21786]: nss_ldap: reconnected to LDAP server ldap://172.17.30.1 after 1 attempt


2. However the another issue is, After 10th Feb 2015 (10-02-2015), partial logs only creating in octopussy server. For example in each device under the log storing path there will be .gz file for every minute for hours from 00 to 23. But after 10th Feb 2015 in all devices log files are partially created. 

Kindly help us to get all logs from devices to octopussy server.

Note: Usually the log size of each day for a device will be approximately 5.1MB but now log files are creating with less than 1MB in octopussy server. Also please note that there is no change in our devices original syslog message's as they are same in size. Only octopussy server is receiving partial logs from all devices.

After  10th Feb 2015, octopussy server receiving partial logs only from all devices.
-------------------------------------------------------------------------------------------------------------
[root@octopussy 09]# du -hsc /var/lib/octopussy/logs/ns6/Unknown/2015/02/*
5.6M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/01
3.7M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/02
4.3M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/03
4.3M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/04
4.2M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/05
4.3M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/06
5.4M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/07
5.3M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/08
4.1M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/09
2.8M	/var/lib/octopussy/logs/ns6/Unknown/2015/02/10
100K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/11
208K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/12
172K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/13
160K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/14
120K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/15
108K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/16
160K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/17
156K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/18
84K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/19
180K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/20
64K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/23
60K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/26
60K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/27
76K	/var/lib/octopussy/logs/ns6/Unknown/2015/02/28
-------------------------------------------------------------------------------------------------------------

Best regards,
Md. Mansoor

**Comment by sebthebert** [comment]
Just to be clear...

you know that `Unknown` means that all these logs are not recognized by Octopussy and are just stored right ? You can not generate reports from unrecognized logs...

It's probably not what you want...

You are supposed to add 'Services' to your 'ns6' Device, 
then you will have `/var/lib/octopussy/logs/ns6/<servicename>/YYYY/MM/DD` directories

The `total number of last minute received logs` in your Octopussy Web homepage decreased since 10-02-2015 ?


Regards,
Sebastien

**Comment by mdmansoor26** [comment]
Hi Sebastien,

Before that I want to tell you something that you are such a wonderful creator and supporter in this world.

Yes I know about "Unknown Logs", actually we have split the logs using services like ssh, cron, clamav (created by us in service tab). The Unknown logs are additional logs from server like ntp, boot message which we are not using for reports.

Yes! the logs count is decreased in Octopussy Web homepage since 10-02-2015.

And one more good news is we have found the issue for the above cause.

One of our firewall creating this issue, when we stop the syslog forward for that particular firewall octopussy works as expected, whenever we start the syslog in firewall we are facing the issue again.

We will sort out the issue in our firewall and get back to you if any support required.

Best regards,
Md. Mansoor
