### ISSUE TITLE
Octopussy perl issue

### ISSUE THREAD

**Issue by srikamani** [sebthebert/Octopussy#618]
Hi I am facing below issue while installing Octopussy log monitor.

```
./INSTALL.sh: line 160: /etc/init.d/syslog: No such file or directory
Shutting down system logger:                               [  OK  ]
Starting system logger:                                    [  OK  ]
[root@syslog octopussy]# Use of uninitialized value $family in numeric ne (!=) at /usr/share/perl5/IO/Socke                                           t/INET6.pm line 226.
Use of uninitialized value $family in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.
Use of uninitialized value $fam_listen in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.
Use of uninitialized value $family in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.
Use of uninitialized value $family in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.
Use of uninitialized value $fam_listen in numeric ne (!=) at /usr/share/perl5/IO/Socket/INET6.pm line 226.
```

I have followed http://www.octopussy.pm/documentation/guides/administrator_guide/01_installation link to install it.

Kindly let us know where I did mistake as I am new for this.

Regards
Srinivas

**Comment by sebthebert** [comment]
Hi,

please, when you submit a new issue, 
follow these [contributing guidelines](https://github.com/sebthebert/Octopussy/blob/master/CONTRIBUTING.md#reporting-issues), especially when it's an installation issue...

What's going on when you launch `/usr/sbin/octopussy start` ?


Regards,
Sebastien

**Comment by sebthebert** [comment]
No news, good news... I close this issue.
