### ISSUE TITLE
Feature required to add date in subject line of Alert

### ISSUE THREAD

**Issue by mdmansoor26** [sebthebert/Octopussy#619]
Hi favourite/great,

I have created a alert and am getting email alert properly, but in my email alert subject line i want to add date, so that i can identify it easily while looking it don't want to check the email alert received time.

Kindly help.

Best regards,
Md. Mansoor

**Comment by sebthebert** [comment]
Hi,

well actually you can already do it.

A not well documented feature (by clicking on the 'Help' button you will be redirected to https://your-octo-server:8888/HELP/en/alerts.html documentation) in Octopussy Alerts message is that you can use reserved words:
  * `__device__` will be replaced by the device that sends log that raise this alert.
  * `__alert__` will be replaced by the alert name of this alert.
  * `__level__` will be replaced by the alert level of this alert.
  * `__log__` will be replaced by the log line that raise this alert.
  * `__field_fieldname__` will be replaced by the value of the field 'fieldname' of the log line.

So in your case, you can use `__field_datetime__` in message subject to get the `datetime` field of your log ! :)

**Comment by mdmansoor26** [comment]
Hi sebthebert,

I have tried the same but which is not worked.

![screenshot from 2015-05-01 02 22 38](https://cloud.githubusercontent.com/assets/8190731/7422256/03952f36-efa9-11e4-8462-de7a0020c5fe.png)

Alert Notification Received without Date in Subject line, result is placed below
------------------------------------------------------------------------------------------------
Subject: [Octopussy]  Local-Login-Failed ns3

Body    :

Dear Team,

Found SSH Login failed Alert. Please check.

ns3: Local-Login-Failed: Critical 

Alert: 2015-04-30T21:48:11+05:30 ns3 sshd[29081]: Failed password for root from 10.1.1.7 port 55775 ssh2
2015-04-30T21:48:12+05:30 ns3 sshd[29081]: Failed password for root from 10.1.1.7 port 55775 ssh2
2015-04-30T21:48:15+05:30 ns3 sshd[29083]: Failed password for root from 10.1.1.7 port 55807 ssh2
------------------------------------------------------------------------------------------------

**Comment by sebthebert** [comment]
Hi,

Ok, I know why you can't display datetime field.

It's actually a bug when you match more than one log... 

I don't have time to fix that right now, only next week...


Regards,

**Comment by sebthebert** [comment]
@mdmansoor26 

I finally took time to fix this issue.

Just get this [Message.pm](https://raw.githubusercontent.com/sebthebert/Octopussy/master/lib/Octopussy/Message.pm) file and restart octopussy:
```
/etc/init.d/octopussy sender-restart
```

Regards,
