### ISSUE TITLE
Special spanish characters on windows log.

### ISSUE THREAD

**Issue by lcsmar** [sebthebert/Octopussy#620]
We have an issue related to special spanish characters like accented ones, from Windows logs. We can´t set right rules to parse logs.

Example copy/pasted from Log wizard:

Pattern:  <@DATE_TIME_ISO@> AGENTSL microsoft-windows-security-auditing<@BRACKETED_STRING@> <@NUMBER@> Se cambi� el estado de una transacci�n. Sujeto: Id. de seguridad: S-<@NUMBER@>-5-<@NUMBER@> Nombre de cuenta: AGENTSL$ Dominio de cuenta: WORKGROUP Id. de inicio de sesi�n: <@HEXA_NUMBER@> Informaci�n de transacci�n: Id. de transacci�n de RM: {F01F83AC-1AA9-11E5-BE51-000C29912FCC} Nuevo estado: <@NUMBER@> Administrador de recursos: {01C2A756-<@NUMBER@>-11E1-8B44-DB2534530CB8} Informaci�n de proceso: Id. de proceso: <@HEXA_NUMBER@> Nombre de proceso: C:\\Windows\\System32\\svchost.exe  
Sample:  2015-06-29T08:51:33-03:00 AGENTSL microsoft-windows-security-auditing[success] 4985 Se cambi� el estado de una transacci�n. Sujeto: Id. de seguridad: S-1-5-18 Nombre de cuenta: AGENTSL$ Dominio de cuenta: WORKGROUP Id. de inicio de sesi�n: 0x3e7 Informaci�n de transacci�n: Id. de transacci�n de RM: {F01F83AC-1AA9-11E5-BE51-000C29912FCC} Nuevo estado: 56 Administrador de recursos: {01C2A756-9464-11E1-8B44-DB2534530CB8} Informaci�n de proceso: Id. de proceso: 0x35c Nombre de proceso: C:\Windows\System32\svchost.exe

**Comment by sebthebert** [comment]
Hello,

it's an encoding issue.
Octopussy works in utf-8. 
Make sure that your logs are sent (by your syslog client) in utf-8,
and that your Octopussy rsyslog is configured for utf-8 as well.
