### ISSUE TITLE
Database Connection is NOT OK !

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#622]
I installed octopussy-1.0.14 on Red Hat Enterprise Linux Client release 5.11 (Tikanga) with perl, v5.8.8 built for x86_64-linux-thread-multi and I am now trying to configure it.

The GUI opens successfully on https://my.server.name:8888 and I am currently yet logged in as admin admin. Unfortunately the System Configuration shows "Database Connection is NOT OK !" for the database setting.
These are at the moment:
Server localhost
User octopussy
Password •••••••••
Base octopussy

A MySQL-Server on the octopussy host is already flawlessly serving databases for other services. I created a database called octopussy, a user called octopussy and gave this user all permissions for that database.

Unfortunately the only log entry I could find is in /var/log/messages and doesn't give me any information:

```
2015-05-29T10:50:41.847994+02:00 myservername octo_WebUI: System Configuration has been modified by admin.
```

Could you give me an idea about where to start to search for the error?

**Comment by XXLRay** [comment]
Okay - it seems to me as if I can't adjust the password from the configuration menu. It always switches back to some default length after I press "Update".

**Comment by XXLRay** [comment]
Is there some kind of log from octopussy that I can read?

**Comment by sebthebert** [comment]
You can see the actual SQL configuration in this file: `/var/lib/octopussy/conf/db.xml`

You can check that these settings are correct with:
```
mysql --user=octopussy --password=octopussy octopussy
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 36
Server version: 5.1.63-0+squeeze1 (Debian)

Copyright (c) 2000, 2011, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables;
+---------------------+
| Tables_in_octopussy |
+---------------------+
| _alerts_            |
+---------------------+
1 row in set (0.00 sec)

mysql>
```

If it's not OK, try to replay the [MySQL part of the Installation](https://github.com/sebthebert/Octopussy_Documentation/blob/master/01_Installation.md#create-octopussy-mysql-database-and-table).

**Comment by XXLRay** [comment]
Thanks a lot. Connection via the mysql command worked fine.

The /var/lib/octopussy/conf/db.xml contained a wrong password. Likely because I created the user on my own. I corrected the password, restarted octopussy but unfortunately the fields in "System Configuration -> Database" are now empty. I can enter data into them but when I click "Update" the fields switch to empty again.

When I restart Octopussy I get the following error message from stopping the daemon. Probably it has something to do with it:

[CRITICAL] Can't open named pipe /var/spool/octopussy/octo_fifo: Interrupted system call at /usr/lib/perl5/site_perl/5.8.8/Octopussy.pm line 81.

**Comment by XXLRay** [comment]
Problem with wrongfully loaded data was a angle bracket in the password (likely xml syntax related - needed to mask it by &lt;). Database Connection is now Okay :)

**Comment by XXLRay** [comment]
I still can't add data to fields via the GUI though. Just tested it for the ldap settings. Could this be a permission issue?

**Comment by XXLRay** [comment]
Yes, it's a permission issue. When I add acls for the user running apache I can change field entries via the GUI. I am not sure if this is an issue in the installation process in general or something I messed up.

**Comment by sebthebert** [comment]
Yes, the user running Octopussy's Apache needs to have write rights on `/var/lib/octopussy/conf/` files and directories.

And the same problem with this error message:
```
[CRITICAL] Can't open named pipe /var/spool/octopussy/octo_fifo: Interrupted system call at /usr/lib/perl5/site_perl/5.8.8/Octopussy.pm line 81.
```
Octopussy user need to have write rights on `/var/spool/octopussy/` files and directories.

You can take a look at [this file](https://github.com/sebthebert/Octopussy/blob/master/LINUX/INSTALL.sh) to check all your write rights issue.
