### ISSUE TITLE
How do I actually see data for a device?

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#623]
I installed octopussy-1.0.14 on Red Hat Enterprise Linux Client release 5.11 (Tikanga) with perl, v5.8.8 built for x86_64-linux-thread-multi and I am now trying to see data from my logs.

I may be missing something obvious but when I try do add a device it does not appear anywhere.

**Comment by sebthebert** [comment]
It's probably related to your [write rights issues](https://github.com/sebthebert/Octopussy/issues/622#issuecomment-108376749).

If you have [properly configured your device to send its logs to Octopussy server](https://github.com/sebthebert/Octopussy_Documentation/blob/master/02_Configuring_Devices.md), you are supposed to see it in the 'Devices' web page.

Then, you need to assign Service(s) to this device to start indexing your logs for this device.

**Comment by sebthebert** [comment]
A short explanation of [How Octopussy works](https://github.com/sebthebert/Octopussy_Documentation/blob/master/04_How_Octopussy_works.md) indicates which directory to look in order to check if you actually receive/index logs

**Comment by XXLRay** [comment]
I have  folders my hosts in /var/lib/octopussy/logs/
Unfortunately neither Incoming nor Unknown contain any logs.
There are remote logs in my /var/log/ from remote servers due to my other rsyslog settings though. So logging itself works in principle.

It looks to me as if no logs are redirected to the folders octopussy needs. Can't I simply tell Octopussy to use my existing remote logs?

**Comment by XXLRay** [comment]
I noticed that /etc/rsyslog.d/10-octopussy.conf includes the entry "$WorkDirectory /var/lib/octopussy/local/rsyslog" but this directory dousn't exist.

**Comment by XXLRay** [comment]
Is there any chance if rsyslog (unlikely in my eyes) or the dispatcher are messing up with putting the logs into the folders required by Octopussy?

**Comment by sebthebert** [comment]
`octo_dispatcher` is running ?

What's going on when you launch: 
```
/etc/init.d/octopussy dispatcher-stop
/etc/init.d/octopussy dispatcher-start
```

**Comment by XXLRay** [comment]
/etc/init.d/octopussy dispatcher-stop
Use of uninitialized value in scalar chomp at /usr/lib/perl5/site_perl/5.8.8/Octopussy.pm line 254.
Use of uninitialized value in kill at /etc/init.d/octopussy line 150.
User defined signal 1
/etc/init.d/octopussy dispatcher-start
octopussy Dispatcher Started.
ERROR: you must define at least one Data Source
mkdir /var/lib/octopussy/conf/devices/: Permission denied at /usr/lib/perl5/site_perl/5.8.8/Octopussy/FS.pm line 54

The owner of /var/lib/octopussy/conf/devices is root.root . This helped to start it without error message:

setfacl -m u:octopussy:rwx /var/lib/octopussy/conf/devices/
setfacl -m u:octopussy:rwx /var/lib/octopussy/conf/

Logs are now created in /var/lib/octopussy/logs/ and I have a list of devices in the GUI.

So I am not sure if the installation process takes care to set the correct permissions or if I messed something up.

Thank you so much for the help. Now I will need some time to play around with it :)
