### ISSUE TITLE
New messages are not applied

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#624]
I installed octopussy-1.0.14 on Red Hat Enterprise Linux Client release 5.11 (Tikanga) with perl, v5.8.8 built for x86_64-linux-thread-multi but had some issues getting the file permissions correct.

Unfortunately none of the log messages seems to get automatically filtered but at least I already have a graph for "Other" :)

What I try to do is:
- Go to the Log Wizard
- Click on the first hostname
- Click add new service (Cyrus_Mail) on the fist message
- Go to the Log Wizard and first host again.
- Choose `Cyrus_Mail` as service for the first message:
Pattern: 	`<@DATE_TIME_ISO@> myhostname imaps[<@NUMBER@>]: imapd:<@WORD@> hard-coded DH parameters`
Sample: 	`2015-06-04T08:47:26+02:00 myhostname imaps[15959]: imapd:Loading hard-coded DH parameters`
- Choose `Mail_Traffic` as table
- Click on Select This Message
- Click on Edit
- Changed name to: `Loading_hard-coded_DH_parameters`
- Changed filter to: `<@DATE_TIME_ISO:datetime@> <@WORD:device@> imaps[<@PID:pid@>]: <@WORD:daemon@>:<@STRING:status@>`
- Clicked on Save Message and go to Service
- My browser console shows "find: cannot get current directory: Permission denied"
- When I go to the Log Wizard the same first message is shown.

Edit 1: The logs seem to be correctly sorted into the subfolders of the services I added to the device.

Permissions look in principle fine to me:

getfacl /var/lib/octopussy/logs/myhostname/Cron/
getfacl: Removing leading '/' from absolute path names
file: var/lib/octopussy/logs/myhostname/Cron
owner: octopussy
group: octopussy
user::rwx
user:octopussy:rwx
group::r-x
mask::rwx
other::r-x

Edit 2: When I set the device type for my devices these are colored in the graph on my home screen but when I click on a device there the depending graph is empty.

**Comment by sebthebert** [comment]
Double check all you directories and files rights...
Everything under `/var/lib/octopussy` should be writable by the `octopussy` user.

**Comment by XXLRay** [comment]
It strange enough works for one of my hosts but not for all others. Could you tell me which folder hold the statistics so that I can check how permissions differ?

**Comment by XXLRay** [comment]
It seems as if I just wasn't patient enough after activation statistics.

**Comment by sebthebert** [comment]
Device(s) statictics are stored in RRD files in `/var/lib/octopussy/rrd/` 
and generate png files in `/var/lib/octopussy/rrd_png/`

**Comment by XXLRay** [comment]
I had done

setfacl -R -m user:octopussy:rwx /var/lib/octopussy/
setfacl -R -m d:user:octopussy:rwx /var/lib/octopussy/

The issue seems to be that it takes quite a while to go through the unknown logs. Is it normal for octopussy to need a few minutes when /var/lib/octopussy/logs/ has 700+ MB?

**Comment by sebthebert** [comment]
Yes, it is normal for Octopussy to take minutes for 700+ MB of logs...

**Comment by XXLRay** [comment]
Thanks for the answer
