### ISSUE TITLE
Octopussy does not save any information after installation

### ISSUE THREAD

**Issue by anfergainst** [sebthebert/Octopussy#627]
Everything was fine under the installation, but when I log with the admin account and try to change any setting, or create any item, nothing happens.
Logs says that configuration was changed sucessfully. But not. Zero changes are made.

Help!

I'm using lastest version under CentOS 6.6

**Comment by anfergainst** [comment]
Permission problem under /var/lib/octopussy/conf/
Solved with chown octopussy:octopussy -R

**Comment by sebthebert** [comment]
You found the solution by yourself, good for you ! :)
