### ISSUE TITLE
Limit logs?

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#628]
Is there any chance to limit the amount of logs stored? They are jamming up hard drive and 30 days of logs would be more than sufficient for me.

**Comment by sebthebert** [comment]
Hello,

of course you can ! :)

I've just updated the [FAQ](https://github.com/sebthebert/Octopussy_Documentation/blob/master/FAQ.md).

**Comment by XXLRay** [comment]
Cool - that already helps. Anyway I noticed that although the default is set to 10 days all services I add have 90 days set.
