### ISSUE TITLE
Devices are intepreted in the wrong way

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#629]
Usually logs come in with the host name that is correctly interpreted as device. Unfortunately I also receive logs that somehow have the IP address of the same host instead which is interpreted as separate device then. Is there a way to map these to a single device somehow?

I furthermore seem to have some log that seem to be malformatted. Now I have a list of devices like exiting, gconfd, last and syslogd. How can I get rid of these. I already stopped them but it's a bit annoying to have them still in the list.

**Comment by sebthebert** [comment]
Hello,

for the second part of your request, take a look at [this answer](https://github.com/sebthebert/Octopussy/issues/606#issuecomment-60478723)

**Comment by XXLRay** [comment]
Hmm - I actually like the automatic device creation.

I decided to put

<parameter name="device_filtering_regexp" value="!(exiting|gconfd|last|syslogd)" />

inside the application tags in /etc/aat/aat.xml where the other parameters are. Is this how it should look like?
Afterwards I restarted octopussy and deleted the old unwanted device entries from the GUI.

It would be great (for me) if you implemented a method to bundle logs for certain devices though.

**Comment by sebthebert** [comment]
Nope, it shouldn't look  like that ! 

`!(exiting|gconfd|last|syslogd)` will only match devicename with `!exiting`, `!gconfd`...
that's the opposite of what you want...

`device_filtering_regexp` is useful when your device names follow a norm.

**Comment by XXLRay** [comment]
Misunderstanding on my side. So the filter actually makes Octopussy ignore devices that match the rule.

**Comment by sebthebert** [comment]
Only devices with hostname matching `device_filtering_regexp` will be handled by Octopussy.
