### ISSUE TITLE
Best practices for variable message body

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#630]
I have an unknown log line for which I need to create a new message and I am not very sure how you would so it the best. The line is:

```
2015-07-29T12:47:14+02:00 myserver abrt: detected unhandled Python exception in './treediscover.py'
````

I chose Service: Abrt, Log Level: Information, Taxonomy: Application, Table: Message and as rule:

```
<@DATE_TIME_ISO:datetime@> <@WORD:device@> <@REGEXP("abrt"):daemon@>: <@REGEXP("detected unhandled Python exception"):msg@><@STRING:msg@>
```

I am especially curious if using the msg tag twice works.

**Comment by sebthebert** [comment]
Hello,

no, you're not supposed to use one field twice...

For that kind of messages, play (use regex) with the REGEXP type:
```
<@DATE_TIME_ISO:datetime@> <@WORD:device@> <@REGEXP("abrt"):daemon@>: <@REGEXP("detected unhandled Python exception in .+"):msg@>
```

**Comment by sebthebert** [comment]
There is a lot of examples in default [Octopussy Services](https://github.com/sebthebert/Octopussy/tree/master/var/lib/octopussy/conf/services).

**Comment by XXLRay** [comment]
Thanks - that's indeed easy to do.
