### ISSUE TITLE
Sourceforge binaries

### ISSUE THREAD

**Issue by k0nsl** [sebthebert/Octopussy#638]
The latest binaries on Sourceforge is from 2014. Do you plan on updating these, or begin publishing binaries here on the GitHub releases page?

Thanks in advance.

**Comment by sebthebert** [comment]
I've just made a new release yesterday !
https://github.com/sebthebert/Octopussy/releases/tag/1.0.16
https://sourceforge.net/projects/syslog-analyzer/files/?source=navbar
